name: Frontend CI/CD

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm ci # Use 'npm ci' for a clean install
        working-directory: ./frontend

      - name: Fix Permissions
        run: chmod +x ./node_modules/.bin/* # Ensure all binaries are executable
        working-directory: ./frontend

      - name: Build
        run: npm run build
        working-directory: ./frontend

      - name: Deploy to Azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'frontend-app'
          slot-name: 'production'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
