name: Mobile CI/CD

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.1'  # Specify the Flutter version you want

      - name: Install Dependencies
        run: flutter pub get
        working-directory: ./mobile  # Navigate to the mobile directory where your pubspec.yaml is

      - name: Build APK
        run: flutter build apk
        working-directory: ./mobile  # Navigate to the mobile directory for build command
